name: YouTube Thumbnail Automation

on:
  schedule:
    # This will run the workflow every 12 minutes
    - cron: "*/12 * * * *"
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  upload_thumbnail:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt in your repo

      # Step 4: Set environment variables using GitHub secrets
      - name: Set environment variables
        run: |
          echo "GCP_CREDENTIALS_BASE64=${{ secrets.GCP_CREDENTIALS_BASE64 }}" >> $GITHUB_ENV
          echo "GCP_TOKEN_BASE64=${{ secrets.GCP_TOKEN_BASE64 }}" >> $GITHUB_ENV

      # Step 5: Run YouTube Thumbnail Script
      - name: Run YouTube Thumbnail Script
        run: |
          python your_script.py  # Replace with the actual filename of your script
